### PR TITLE
Added link to hBPF project

### PR DESCRIPTION
**Pull request by rprinz08**

### CODE REVIEW

**Comment by Dantali0n** [comment]
Cool project, migen is an interesting choice there is also nmigen would be interesting to know some backstory behind the tools used. I'd think this make a great addition to the list especially as the hardware offloading category is comparatively small.

**Comment by qmonnet** [comment]
Woops, this one slipped through the cracks, apologies.
@rprinz08 Same remark as on ebpf.io, would you mind using a dash instead of the `=`, please?

**Comment by rprinz08** [comment]
No problem, changed '=' to '-'

**Review by qmonnet — APPROVED** [review]

**Comment by qmonnet** [comment]
Apologies, I didn't mean to close the PR. I tried to address the conflict on the first commit (before your newer merge commit) by squashing into a single commit, and pushing on your branch. But I messed up somewhere and pushed from my `master` branch instead, erasing your commit on _your_ `master` and thus automatically closing the PR (no more commits in it). I can't push again because I don't have the permissions anymore, the PR being closed.

Anyway. I just merged your commit locally to `master` and pushed, the link is here in the readme.md, the only difference is that this PR is mark as “closed“ when it should really be “merged”. Hopefully not a big deal. Sorry again for the mix up.

**Pull request closed without merging**
