### PR TITLE
Add a blog post about ebpf internals

### PR DESCRIPTION
**Pull request by rabbitstack**
A blog post covering the basics of eBPF internals as well as code samples in Go on how to build and load a minimal eBPF program into the kernel.

### CODE REVIEW

**Comment by yuzibo** [comment]
Thanks for adding tutorial about ebpf.
But i think there are not need to delete original post.

**Comment by rabbitstack** [comment]
>But i think there are not need to delete original post.

Sorry, I'm not sure what did you mean.

**Comment by yuzibo** [comment]
Emm,in my view you delete [Extending extended BPF] string also.I am not sure about this maybe broswer issue.sorry about confusion.

**Comment by rabbitstack** [comment]
This is what github's diff reflects:

ebpf

Also, if you navigate to the fork of this repo with the changed added, all looks good to me:
https://github.com/rabbitstack/awesome-ebpf

**Comment by yuzibo** [comment]
Got it.
Thanks again.

**Comment by rabbitstack** [comment]
@yuzibo good to merge?

**Comment by yuzibo** [comment]
Sorry for late reply.
I have no permission to merge the RP.
But i think we can @zoidbergwill

**Comment by rabbitstack** [comment]
no worries. Let's wait for @zoidbergwill

**Comment by otisg** [comment]
👍 for merging this :)

**Comment by zoidbergwill** [comment]
Looks good to me. Thanks for your contribution. :+1:

**Pull request merged**
