### PR TITLE
Add a paper for eBPF-based real-time edge computing

### PR DESCRIPTION
**Pull request by yuzibo**
This is an interesting paper for edge computing with ebpf 
Signed-off-by: Bo YU <tsu.yubo@gmail.com>

### CODE REVIEW

**Comment by qmonnet** [comment]
Hi, the link does not point to the paper but to a GitHub repo instead. The README from that repo is not so clear (in my opinion) about what the project does, it misses a two-line intro/description at the very least. And the research paper linked from that GitHub page is not freely accessible :(.

Also, what does “The rarely application about eBPF” mean?

**Comment by yuzibo** [comment]
Hi,
Sorry for confused description.
The github repo is ready for  experiment step about the paper.
And i will request author of the paper offer the paper pdf in github if he will do.

 "The rarely application about eBPF" i mean that in ebpf is less about application than
networking and tracing in kernel. For example Iot, edge computing usage.
Although it is unconvincing about ebpf's intention in my view.

I will update the commit if everything is ok.

**Comment by yuzibo** [comment]
Hi,
Due to copyright of paper issue,the author can not offer the paper freely other than [link](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8407006&tag=1)
Is that will be ok?

**Comment by qmonnet** [comment]
I'll leave it to zoidbergwill, but for me it's not. No free access means the link will be broken for most people.

Also, are you sure the paper is about an “important” use case for eBPF? What I mean is that eBPF will be used in more and more stuff, and I don't expect all papers mentioning it, or using it only a little, to be added to the list. They should present very innovative use cases, or have a “significant” impact, to be cited here in my opinion. In this case it's hard to tell, since I can't read the paper :/.

**Comment by yuzibo** [comment]
Yeah,i know your means.
But the paper used eBPF to its application from different view indeed.
Maybe it is useful for  research person.

**Comment by qmonnet** [comment]
I am still opposed to the addition of this link, on the same basis. Mostly inaccessible links are a no-go, and even though it _could_ possibly be useful to researchers, they can find it by other means. In my opinion, it does not belong to a list that seeks to remain curated.

I'm closing the PR, leaving it to zoidbergwill to reopen it if he is of a different mind about this.

**Comment by zoidbergwill** [comment]
I'd love to see the authors uploading the paper to an open journal where more folks could benefit from it and access it.

**Pull request closed without merging**
