### PR TITLE
Restart list with Dive into BPF List

### PR DESCRIPTION
**Pull request by zoidbergwill**
Based on these:

https://qmonnet.github.io/whirl-offload/2016/09/01/dive-into-bpf/#what-is-bpf
https://github.com/qmonnet/whirl-offload/blob/gh-pages/_posts/2016-09-01-dive-into-bpf.md

I've tried to trim it a little and format it consistently and with a table of contents. Not sure if it should be structured of if I should trim anything. The tone is maybe different from what it should be for this, but also it's nice cuz it has character.

It's great that this now covers cBPF and XDP as well, imho, so we can fit more stuff into this list which is related.

### CODE REVIEW

**Comment by qmonnet** [comment]
Hi @zoidbergwill,

First: this is *your* list, so whatever I suggest in this comment, feel free to do as you like in the end :)

So, thank you for the credit and for appreciating my post this much! :). However, it looks like a bit bloated with text in my opinion for an *awesome-something*. Maybe it might be worth to trim more text. In particular:
* The introduction could be shortened. Plus it's not totally up-to-date (nothing about cgroups, etc.).
* Most items could maybe be reformatted to display the links at the beginning of the lines, so that readers can find them immediately. And maybe we want just one link per line?
* I emphasised some words, precisely because they were hard to find in the middles of the paragraphs. Maybe we can remove this formatting.
* This is supposed to be a curated list, not an exhaustive one, so maybe we could remove some old presentations. The ones from 2015 might not be up-to-date and deserve as much exposure today. Better have a small number of excellent presentations that a huge number with overlapping contents.
* On a second thought, I don't know if I should have made a distinction between slides from presentations and technical documentation. Maybe focus on grouping them by topic instead. Readers don't really care (I think?) what form has the document, as long as it contains the information they want (save maybe for scientific papers that do deserve their section, much harder to read?)
* Please rework the “Troubleshooting” section. Keep the links if you want, but remove my own tips, they're not up-to-date.

I have been considering myself to write a newer version of my post in a more synthetic way, so I think this awesome list is really the occasion to get the links in a more “immediate” fashion. If some folks *do* want more text, there is still my original post, that already got a correct exposure. Plus if you want contributions from other people—which is also really hard to get on my blog—it will probably be much easier if they have to add just one sentence instead of a full paragraph-long description to remain in the style of the list.

At least, that's my opinion :)

And just as a side note, you can also find some additional links [here](https://www.iovisor.org/technology/ebpf) and [there](https://github.com/iovisor/bcc/blob/master/LINKS.md), I did not try to include them all; although you might have to do some sorting yourself, all of them are probably not worth adding to the list.

**Comment by zoidbergwill** [comment]
@qmonnet Awesome, thanks. Yeah, this PR is a bit of a work in progress. I completely agree with all your feedback. I'd like to keep it high SNR, so getting rid of out-dated information, duplicated information, and trimming all the descrptions, so they're all `{link}: {short descrption}`

I think merging learning blogs/slides/talks into a single section is a great idea. Will work on it later this evening.

**Comment by qmonnet** [comment]
Hi @zoidbergwill,

I hope I did not discourage you with all those TODOs :-). Sorting out everything and trimming through the outdated links looks time consuming.

If I can add some piece of advice: Don't overthink it! Don't hesitate to start with something simple. Pick the links you liked in my list or anywhere else, you don't have to make something exhaustive or perfect from start. You could possibly build on top of what is live already, and not necessarily write something from scratch. I think several people, including myself, are willing to see this awesome-ebpf and to help completing it.

Cheers!

**Comment by zoidbergwill** [comment]
Hi @qmonnet, thanks for that.

Don't worry, you didn't discourage me. Your TODOs were really inspiring, unfortunately life has been a little busy, but I'm keen to get this merged.

**Comment by zoidbergwill** [comment]
I still need to do the pruning of some outdated links and see if there are any crucial ones we're missing from https://www.iovisor.org/technology/ebpf and https://github.com/iovisor/bcc/blob/master/LINKS.md

**Comment by qmonnet** [comment]
So I saw your last comments and your invitation to collaborate (thanks for your trust!) around Christmas, was busy (like everyone else! :) ) and then forgot to answer…

Ok, good! Nice work on those last commits. I still think we could simplify (a lot) item descriptions and remove some stuff. I've been reworking the first section on top of this branch, that's available [on this branch](https://github.com/qmonnet/awesome-ebpf/tree/qmonnet-qmonnet). Consider it as a RFC (I'm sorry I just saw your last commits and may have use italics again in my patches, and I did not use the linter; so just a RFC, really), I'd be interested in your feedback.

**Comment by zoidbergwill** [comment]
Hey @qmonnet 

Awesome, thanks!

Yeah, agreed. I'd love to trim some of the links and the descriptions. Will merge your branch in, and I can get rid of some italics again if I need to. It wasn't too much of a mission.

**Comment by zoidbergwill** [comment]
Will take a look at this some more later today.

**Comment by zoidbergwill** [comment]
I'm still keen to get rid of stuff, though we could merge before that?

**Comment by zoidbergwill** [comment]
Then clean up and add new stuff as we go?

**Comment by qmonnet** [comment]
Do you mean get rid of stuff in the first section? (_Resources_) Or mostly in the next sections (that I didn't reformat)?

Anyway feel free to handle this and to merge whenever you want, you're the chief here :)

Just some advice maybe:
* If you could fix the _Hardware offload_ subsection before that, I realized a few days ago that I messed up with the text :(.
* You might want to update your TODO at the beginning to tell readers that the verbose sections are susceptible to change a lot, … or whatever you might want to tell them :).

**Comment by zoidbergwill** [comment]
That all sounds great. Mainly in the later sections, I think. Not even sure what exactly, just related to the earlier comments on some of the links possibly overlapping or being outdated/redundant.

Will take a look at those. Markdown is a little annoying with how it treats newlines. 😞 

> You might want to update your TODO at the beginning to tell readers that the verbose sections are susceptible to change a lot, … or whatever you might want to tell them :).

Will totally do that. Great idea. Thanks.

**Comment by zoidbergwill** [comment]
I'm thinking of just adding a note that looks something like this:

```
> Note: eBPF is an exciting piece of technology, and it's ecosystem is constantly evolving. We'd love help from _you_ to keep this awesome list up to date, and improve its signal-to-noise ratio in anyway we can. Please feel free to leave [any feedback](https://github.com/zoidbergwill/awesome-ebpf/issues).
```

Though I do think it's a great idea to highlight what exactly we're planning on re-working when we get a chance, in case folks are keen to help as well.

**Comment by qmonnet** [comment]
Yeah, totally makes sense.

I'm pushing a bunch of additional commit to this PR, feel free to comment or reject if you don't like them.

**Comment by zoidbergwill** [comment]
Those look great!

**Comment by zoidbergwill** [comment]
Thanks for all the awesome work @qmonnet

**Pull request merged**
