### PR TITLE
add merbridge in Projects Related to eBPF

### PR DESCRIPTION
**Pull request by pacoxu**
Fixes https://github.com/zoidbergwill/awesome-ebpf/issues/72

### CODE REVIEW

**Comment by qmonnet** [comment]
> like crossing an Einstein-Rosen Bridge

This is a cool reference, but not really descriptive. Could we have something a bit more helpful? I see the project has this on its website:

> Merbridge replaces iptables rules with eBPF to intercept traffic. It also combines msg_redirect to reduce latency with a shortened datapath between sidecars and services.

(I don't mind mixing the two if it's not too long, let's just _not_ have _only_ the bridge.)

And thank you for the PR!

**Review by qmonnet — CHANGES_REQUESTED** [review]
> like crossing an Einstein-Rosen Bridge

This is a cool reference, but not really descriptive. Could we have something a bit more helpful? I see the project has this on its website:

> Merbridge replaces iptables rules with eBPF to intercept traffic. It also combines msg_redirect to reduce latency with a shortened datapath between sidecars and services.

(I don't mind mixing the two if it's not too long, let's just _not_ have _only_ the bridge.)

And thank you for the PR!

**Comment by pacoxu** [comment]
Updated. 

[The website](https://merbridge.io/)

**Review by qmonnet — APPROVED** [review]
Great, thanks!

**Pull request merged**
