### PR TITLE
Academic papers

### PR DESCRIPTION
**Pull request by pchaigno**
A few academic papers on BPF/eBPF. I also changed the format to include authors and the conference name or book title.

I did not find some of the papers for free on the web, don't know if we should still keep them on the list. Also, the BPF+ paper is available for free but it's a `.ps.gz` format, not sure if I should link to that instead of ACM.

### CODE REVIEW

**Comment by zoidbergwill** [comment]
Awesome! Thanks for the contribution. 

I think it's worth having the non-free ones with a disclaimer, and then maybe linking to both formats?

I'm gonna re-format the whole list in #3, so we can rebase this branch as soon as that PR is merged?

**Comment by qmonnet** [comment]
Yeah keeping the links with a disclaimer sounds great!

**Comment by pchaigno** [comment]
> I'm gonna re-format the whole list in #3, so we can rebase this branch as soon as that PR is merged?

Sure 👍

**Comment by zoidbergwill** [comment]
@pchaigno if you don't mind fitting your contributions into the new list? Or I'll take a look on Monday.

Thanks for your contributions. 🙏

**Comment by qmonnet** [comment]
@pchaigno Would you mind rebasing when you have the time, please?

**Comment by zoidbergwill** [comment]
Maybe we should still try put these in? Will take a look when I have a chance.

**Pull request closed without merging**
